remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

# Directories for layouts and includes
layouts_dir: _layouts
includes_dir: _includes

# Google Analytics
google_analytics: G-D0CEQB4V20

title: Xavier Morera  

