remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  # Optional plugins (add if needed)
  # - jekyll-seo-tag
  # - jekyll-sitemap

# Optional site metadata
title: "My Awesome Site"
description: "A custom site using the Tactile theme on GitHub Pages."
url: "https://your-username.github.io"
baseurl: ""  # Set to "/repo-name" if not using a custom domain

# Directories for layouts and includes (optional, only if you're using custom directories)
layouts_dir: _layouts
includes_dir: _includes

# Optional permalink structure for cleaner URLs
permalink: /:title/
