remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# Google Analytics
google_analytics: G-D0CEQB4V20

title: Xavier Morera (Lupo.AI)
description: Learning & Development @ Lupo.AI | Author @ Pluralsight (Gen AI, ML, Dev, Python, .NET, Data) | Revenue Booster | Biking Aficionado 🚴‍♂️
